workspace:
  base: /go
  path: src/toroid.io/drone-plugins/drone-kicad

pipeline:
  buildgo:
    image: golang
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  scipts:
    image: bravissimolabs/alpine-git
    commands:
      - git clone https://git.toroid.io/KiCad/ci-scripts.git

  latest:
    image: plugins/docker
    repo: toroid/drone-kicad
    tags: [latest, 0.2]
    when:
      branch: master
      event: push
